name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Sadece main branch pushlarında çalışsın

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repo'yu çek
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Python kurulum
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Bağımlılıkları yükle ve testleri çalıştır
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: pytest

      # 4. Docker imajı build et
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} .

      # 5. Docker Hub'a push et
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}

      # 6. Sunucuya SSH ile bağlan ve container'ı güncelle
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
